module Apologist
  module Models
    type user_create_with_list_params =
      { body: ::Array[Apologist::UserAPI] }
      & Apologist::Internal::Type::request_parameters

    class UserCreateWithListParams < Apologist::Internal::Type::BaseModel
      extend Apologist::Internal::Type::RequestParameters::Converter
      include Apologist::Internal::Type::RequestParameters

      attr_reader body: ::Array[Apologist::UserAPI]?

      def body=: (::Array[Apologist::UserAPI]) -> ::Array[Apologist::UserAPI]

      def initialize: (
        ?body: ::Array[Apologist::UserAPI],
        ?request_options: Apologist::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Apologist::UserAPI],
        request_options: Apologist::RequestOptions
      }
    end
  end
end
