module Apologist
  module Models
    type user_create_params =
      {  } & Apologist::Internal::Type::request_parameters

    class UserCreateParams < Apologist::Models::UserAPI
      extend Apologist::Internal::Type::RequestParameters::Converter
      include Apologist::Internal::Type::RequestParameters

      def initialize: (?request_options: Apologist::request_opts) -> void

      def to_hash: -> { request_options: Apologist::RequestOptions }
    end
  end
end
