module Apologist
  module Resources
    class Pet
      def create: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: Apologist::PetAPI::Category,
        ?status: Apologist::Models::PetAPI::status,
        ?tags: ::Array[Apologist::PetAPI::Tag],
        ?request_options: Apologist::request_opts
      ) -> Apologist::PetAPI

      def retrieve: (
        Integer pet_id,
        ?request_options: Apologist::request_opts
      ) -> Apologist::PetAPI

      def update: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: Apologist::PetAPI::Category,
        ?status: Apologist::Models::PetAPI::status,
        ?tags: ::Array[Apologist::PetAPI::Tag],
        ?request_options: Apologist::request_opts
      ) -> Apologist::PetAPI

      def delete: (
        Integer pet_id,
        ?request_options: Apologist::request_opts
      ) -> nil

      def find_by_status: (
        ?status: Apologist::Models::PetFindByStatusParams::status,
        ?request_options: Apologist::request_opts
      ) -> Apologist::Models::pet_find_by_status_response

      def find_by_tags: (
        ?tags: ::Array[String],
        ?request_options: Apologist::request_opts
      ) -> Apologist::Models::pet_find_by_tags_response

      def update_with_form: (
        Integer pet_id,
        ?name: String,
        ?status: String,
        ?request_options: Apologist::request_opts
      ) -> nil

      def upload_image: (
        Integer pet_id,
        body: Apologist::Internal::file_input,
        ?additional_metadata: String,
        ?request_options: Apologist::request_opts
      ) -> Apologist::Models::PetUploadImageResponse

      def initialize: (client: Apologist::Client) -> void
    end
  end
end
